[build]
  command = "pip install --no-cache-dir Flask==2.3.3 python-dotenv==1.0.0"
  publish = "static"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  PYTHON_VERSION = "3.10"
  PIP_NO_CACHE_DIR = "1"
  NETLIFY_USE_YARN = "false"
